# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
    ]
