# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_patient_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Customer',
        ),
    ]
