# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20181013_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_photo', models.ImageField(upload_to='media/staff_img')),
                ('depart_name', models.CharField(max_length=60)),
                ('depart_description', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
