# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depart_photo',
            field=models.ImageField(upload_to='media/staff_img/Department'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Doc_photo',
            field=models.ImageField(upload_to='media/staff_img/doctors'),
        ),
    ]
