# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20181017_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depart_description',
            field=models.CharField(max_length=1000),
        ),
    ]
