# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20181018_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depart_name',
            field=models.CharField(max_length=50),
        ),
    ]
