# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20181018_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='depart_doc',
            field=models.ManyToManyField(to='app1.Doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Doc_Speciality',
            field=models.CharField(choices=[('GYNECOLOGY', 'Gynecology'), ('PEDIATRICS', 'Pediatrics'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPAEDICS', 'Orthopaedics')], default=None, max_length=50, verbose_name='DOCTOR SPECIALITY'),
        ),
    ]
