# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20181020_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='depart_doc',
        ),
    ]
