# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20181020_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('dc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Doctors')),
            ],
        ),
    ]
