# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depart_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Doctors'),
        ),
    ]
