# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20181024_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='depart_name',
            new_name='depart_docname',
        ),
    ]
