# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20181024_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='depart_Speciality',
            field=models.CharField(choices=[('GYNECOLOGY', 'Gynecology'), ('PEDIATRICS', 'Pediatrics'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPAEDICS', 'Orthopaedics')], default=None, max_length=50, verbose_name='DOCTOR SPECIALITY'),
        ),
    ]
