# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_department_depart_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='depart_Speciality',
        ),
        migrations.RemoveField(
            model_name='department',
            name='depart_docname',
        ),
        migrations.AddField(
            model_name='department',
            name='depart_name',
            field=models.CharField(choices=[('GYNECOLOGY', 'Gynecology'), ('PEDIATRICS', 'Pediatrics'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPAEDICS', 'Orthopaedics')], default=None, max_length=50, verbose_name='Department'),
        ),
    ]
