# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20181024_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='dc_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=None, help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='num_ppl',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=None, help_text='Starting time', verbose_name='Starting time'),
        ),
    ]
