# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20181025_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dc_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.Doctors'),
        ),
    ]
