# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20181026_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=20)),
                ('date_appointment', models.DateField(blank=True)),
                ('s_time', models.TimeField(blank=True)),
                ('fees', models.IntegerField(default=300)),
                ('no_ppl', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
